# Update railway.toml with different build settings
@"
[build]
builder = "nixpacks"

[deploy]
startCommand = "cd ums_project && java -jar target/*.jar"
"@ | Out-File -FilePath "railway.toml" -Encoding utf8